### PR TITLE
feat: convert circuit json to dsn

### PR DESCRIPTION
**Pull request by imrishabh18**
This circuit json was converted to the bottom pcb json shared which is very close to the og pcb json

## Circuit Json
```
[
  {
    "type": "pcb_smtpad",
    "pcb_smtpad_id": "RoundRect[T]Pad_540x640_135.514_um_0.000000_0_1",
    "pcb_component_id": "Resistor_SMD:R_0402_1005Metric",
    "pcb_port_id": "RoundRect[T]Pad_540x640_135.514_um_0.000000_0_1",
    "shape": "rect",
    "x": 149.48,
    "y": 105,
    "width": 0.54,
    "height": 0.64,
    "layer": "top",
    "port_hints": [
      "1"
    ]
  },
  {
    "type": "pcb_smtpad",
    "pcb_smtpad_id": "RoundRect[T]Pad_540x640_135.514_um_0.000000_0_2",
    "pcb_component_id": "Resistor_SMD:R_0402_1005Metric",
    "pcb_port_id": "RoundRect[T]Pad_540x640_135.514_um_0.000000_0_2",
    "shape": "rect",
    "x": 150.5,
    "y": 105,
    "width": 0.54,
    "height": 0.64,
    "layer": "top",
    "port_hints": [
      "2"
    ]
  },
  {
    "type": "pcb_smtpad",
    "pcb_smtpad_id": "RoundRect[T]Pad_900x950_225.856_um_0.000000_0_1",
    "pcb_component_id": "Capacitor_SMD:C_0603_1608Metric",
    "pcb_port_id": "RoundRect[T]Pad_900x950_225.856_um_0.000000_0_1",
    "shape": "rect",
    "x": 154.245,
    "y": 105,
    "width": 0.9,
    "height": 0.95,
    "layer": "top",
    "port_hints": [
      "1"
    ]
  },
  {
    "type": "pcb_smtpad",
    "pcb_smtpad_id": "RoundRect[T]Pad_900x950_225.856_um_0.000000_0_2",
    "pcb_component_id": "Capacitor_SMD:C_0603_1608Metric",
    "pcb_port_id": "RoundRect[T]Pad_900x950_225.856_um_0.000000_0_2",
    "shape": "rect",
    "x": 155.795,
    "y": 105,
    "width": 0.9,
    "height": 0.95,
    "layer": "top",
    "port_hints": [
      "2"
    ]
  },
  {
    "type": "pcb_trace",
    "pcb_trace_id": "bff2dc94-ce6d-46ea-b3f3-c4d4a34a12f0",
    "source_trace_id": "Net-(C1-Pad1)",
    "route_thickness_mode": "constant",
    "should_round_corners": false,
    "route": [
      {
        "route_type": "wire",
        "x": 150.5,
        "y": 105,
        "width": 0.2,
        "layer": "top"
      },
      {
        "route_type": "wire",
        "x": 154.54,
        "y": 105,
        "width": 0.2,
        "layer": "top"
      }
    ]
  },
  {
    "type": "pcb_board",
    "pcb_board_id": "4db82917-cd24-45fb-bd07-830ca5b5db42",
    "outline": [
      {
        "x": 158,
        "y": 108
      },
      {
        "x": 147.5,
        "y": 108
      },
      {
        "x": 147.5,
        "y": 102
      },
      {
        "x": 158,
        "y": 102
      },
      {
        "x": 158,
        "y": 108
      }
    ]
  }
]
```

## Pcb Json

```
{
  "filename": "",
  "parser": {
    "string_quote": "",
    "host_version": "",
    "space_in_quoted_tokens": "",
    "host_cad": ""
  },
  "resolution": {
    "unit": "um",
    "value": 10
  },
  "unit": "um",
  "structure": {
    "layers": [
      {
        "name": "F.Cu",
        "type": "signal",
        "property": {
          "index": 0
        }
      },
      {
        "name": "B.Cu",
        "type": "signal",
        "property": {
          "index": 1
        }
      }
    ],
    "boundary": {
      "path": {
        "layer": "pcb",
        "width": 0,
        "coordinates": [
          158000,
          -108000,
          147500,
          -108000,
          147500,
          -102000,
          158000,
          -102000,
          158000,
          -108000
        ]
      }
    },
    "via": "Via[0-1]_600:300_um",
    "rule": {
      "clearances": [
        {
          "value": 200
        },
        {
          "value": 200,
          "type": "default_smd"
        },
        {
          "value": 50,
          "type": "smd_smd"
        }
      ],
      "width": 200
    }
  },
  "placement": {
    "components": [
      {
        "name": "Resistor_SMD:R_0402_1005Metric",
        "place": {
          "refdes": "Resistor_SMD:R_0402_1005Metric",
          "PN": "Resistor_SMD:R_0402_1005Metric",
          "x": 149990,
          "y": -105000,
          "side": "front",
          "rotation": 0
        }
      },
      {
        "name": "Capacitor_SMD:C_0603_1608Metric",
        "place": {
          "refdes": "Capacitor_SMD:C_0603_1608Metric",
          "PN": "Capacitor_SMD:C_0603_1608Metric",
          "x": 155020,
          "y": -105000,
          "side": "front",
          "rotation": 0
        }
      }
    ]
  },
  "library": {
    "images": [
      {
        "name": "Resistor_SMD:R_0402_1005Metric",
        "outlines": [],
        "pins": [
          {
            "padstack_name": "RoundRect[T]Pad_540x640_135.514_um_0.000000_0",
            "pin_number": 1,
            "x": -510,
            "y": 0
          },
          {
            "padstack_name": "RoundRect[T]Pad_540x640_135.514_um_0.000000_0",
            "pin_number": 2,
            "x": 510,
            "y": 0
          }
        ]
      },
      {
        "name": "Capacitor_SMD:C_0603_1608Metric",
        "outlines": [],
        "pins": [
          {
            "padstack_name": "RoundRect[T]Pad_900x950_225.856_um_0.000000_0",
            "pin_number": 1,
            "x": -775,
            "y": 0
          },
          {
            "padstack_name": "RoundRect[T]Pad_900x950_225.856_um_0.000000_0",
            "pin_number": 2,
            "x": 775,
            "y": 0
          }
        ]
      }
    ],
    "padstacks": [
      {
        "name": "RoundRect[T]Pad_540x640_135.514_um_0.000000_0",
        "shapes": [
          {
            "shapeType": "polygon",
            "layer": "F.Cu",
            "width": 0,
            "coordinates": [
              -270,
              320,
              270,
              320,
              270,
              -320,
              -270,
              -320,
              -270,
              320
            ]
          }
        ],
        "attach": "off"
      },
      {
        "name": "RoundRect[T]Pad_900x950_225.856_um_0.000000_0",
        "shapes": [
          {
            "shapeType": "polygon",
            "layer": "F.Cu",
            "width": 0,
            "coordinates": [
              -450,
              475,
              450,
              475,
              450,
              -475,
              -450,
              -475,
              -450,
              475
            ]
          }
        ],
        "attach": "off"
      }
    ]
  },
  "network": {
    "nets": [
      {
        "name": "Net-(C1-Pad1)",
        "pins": [
          "Resistor_SMD:R_0402_1005Metric-2"
        ]
      }
    ],
    "classes": [
      {
        "name": "kicad_default",
        "description": "",
        "net_names": [
          "Net-(C1-Pad1)"
        ],
        "circuit": {
          "use_via": "Via[0-1]_600:300_um"
        },
        "rule": {
          "clearances": [
            {
              "value": 200
            }
          ],
          "width": 200
        }
      }
    ]
  },
  "wiring": {
    "wires": [
      {
        "path": {
          "layer": "F.Cu",
          "width": 200,
          "coordinates": [
            150500,
            -105000,
            154540,
            -105000
          ]
        },
        "net": "Net-(C1-Pad1)",
        "type": "route"
      }
    ]
  }
}
```

### CODE REVIEW

**Comment by seveibar** [comment]
we should throw in a smoke test or even a quick svg snapshot test

**Review by seveibar — APPROVED** [review]
highly recommend a a small test!

**Comment by seveibar** [comment]
Also instead of calling it `PcbJson` we should call it `DsnJson`, because there are many pcb json types (including `KicadJson`)

**Comment by imrishabh18** [comment]
I was testing on my end, forgot to add the test file. Will add that

**Pull request merged**
